-- MySQL Script generated by MySQL Workbench
-- Fri Jan 12 00:17:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LongboxTesting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LongboxTesting` ;

-- -----------------------------------------------------
-- Schema LongboxTesting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LongboxTesting` DEFAULT CHARACTER SET utf8 ;
USE `LongboxTesting` ;

-- -----------------------------------------------------
-- Table `LongboxTesting`.`API_Dump`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LongboxTesting`.`API_Dump` ;

CREATE TABLE IF NOT EXISTS `LongboxTesting`.`API_Dump` (
  `card_name` VARCHAR(148) NOT NULL,
  `set_name` VARCHAR(8) NOT NULL,
  `collector_code` VARCHAR(8) NOT NULL,
  `typeline` VARCHAR(64) NOT NULL,
  `color` VARCHAR(5) NULL DEFAULT NULL,
  `color_identity` VARCHAR(5) NULL DEFAULT NULL,
  `mana_cost` VARCHAR(16) NULL DEFAULT '',
  `cmc` DECIMAL(3,1) UNSIGNED NOT NULL DEFAULT '0.0',
  `oracle_text` VARCHAR(512) NULL DEFAULT '',
  `market_average` DECIMAL(8,2) UNSIGNED NULL DEFAULT '0.00',
  `scryfall_uri` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`set_name`, `collector_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LongboxTesting`.`User_Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LongboxTesting`.`User_Cards` ;

CREATE TABLE IF NOT EXISTS `LongboxTesting`.`User_Cards` (
  `quantity` INT UNSIGNED NOT NULL DEFAULT '1',
  `API_Dump_set` VARCHAR(4) NOT NULL,
  `API_Dump_collector_code` VARCHAR(3) NOT NULL,
  `folder_tag` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`API_Dump_set`, `API_Dump_collector_code`),
  INDEX `fk_User_Cards_API_Dump_idx` (`API_Dump_set` ASC, `API_Dump_collector_code` ASC) VISIBLE,
  CONSTRAINT `fk_User_Cards_API_Dump`
    FOREIGN KEY (`API_Dump_set` , `API_Dump_collector_code`)
    REFERENCES `LongboxTesting`.`API_Dump` (`set_name` , `collector_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `LongboxTesting` ;

-- -----------------------------------------------------
-- Placeholder table for view `LongboxTesting`.`DatabaseView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LongboxTesting`.`DatabaseView` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `LongboxTesting`.`User's Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LongboxTesting`.`User's Cards` (`id` INT);

-- -----------------------------------------------------
-- View `LongboxTesting`.`DatabaseView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LongboxTesting`.`DatabaseView`;
DROP VIEW IF EXISTS `LongboxTesting`.`DatabaseView` ;
USE `LongboxTesting`;
CREATE  OR REPLACE VIEW `DatabaseView` AS SELECT * FROM api_dump;

-- -----------------------------------------------------
-- View `LongboxTesting`.`User's Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LongboxTesting`.`User's Cards`;
DROP VIEW IF EXISTS `LongboxTesting`.`User's Cards` ;
USE `LongboxTesting`;
CREATE  OR REPLACE VIEW `User's Cards` AS select * from user_cards;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
